In [1]:
import torch

In [2]:
t = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [3]:
print(t, t.dtype, t.shape)

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.int64 torch.Size([2, 3])


In [4]:
T = torch.Tensor([[1, 2, 3], [4, 5, 6]])

In [6]:
print(T, T.dtype, T.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.float32 torch.Size([2, 3])


In [7]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])
t3 = torch.cat([t1, t2])
t3

tensor([1, 2, 3, 4, 5, 6])

In [10]:
t4 = torch.stack([t1,t2])
t4

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
t

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
t.view((3, 2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [13]:
t

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([[2,2,2],[2,2,2]])
t3 = torch.add(t1, t2)
t3

tensor([[3, 4, 5],
        [3, 4, 5]])

In [15]:
t4 = torch.mul(t1, t2)
t4

tensor([[2, 4, 6],
        [2, 4, 6]])